globus-gladier/gladier-xpcs

gladier_xpcs/online_processing.py, scripts/get_status.py, scripts/xpcs_corr_client.py
This should allow you to call into the XPCSClient for fetching the status given a run id. It doesn't change the original behavior of the `xpcs_corr_client.py` script.
=> Added 'get_status' command

requirements.txt, tool-requirements.txt
Tool requirements are only needed on the funcx endpoint or container
They are not needed on the Gladier client that deploys the flow.
=> refactor: Moved tool requirements into their own file

xpcs_portal/xpcs_index/apps.py, xpcs_portal/xpcs_index/views.py
Previously, a hard-coded filter was set on all xpcs search requests.
This makes that setting configurable.
@tskluzac Does this make sense for your project?
=> chore: Move default filters in search views to app.py as setting

gladier_xpcs/flow_online.py, gladier_xpcs/flow_reprocess.py, gladier_xpcs/tools/__init__.py, gladier_xpcs/tools/acquire_nodes.py
Having the AcquireNodes step will ensure we don't have timeouts
due to not being able to acquire nodes on the corr task.
=> Rename 'WarmNodes' to 'AquireNodes'. Add to Online Processing.

xpcs_portal/testing/settings.py, xpcs_portal/xpcs_index/apps.py, xpcs_portal/xpcs_index/fields.py
This simply removes the references to petrel and trusts the records instead, which are all now set to records on eagle.
=> Migrate to eagle endpoint

gladier_xpcs/flow_online.py
This tool requires special write permissions on Clutch, which I don't have. Disabling it for now so it doesn't cause runs to stall.
=> Temporarily disable Transfer To Clutch tool.

gladier_xpcs/flow_base.py, gladier_xpcs/flow_gpu.py, gladier_xpcs/flow_online.py
A bit of refactoring to remove duplicated code between the online/gpu flows. The combine base client contains the fix for not doing retries on 404.
=> Refactor clients, fix retry on non-transient error codes (like 404)

scripts/xpcs_corr_gpu_client.py
@banubot Merging these now, but I want to note them for you here. The index change from test to prod is below, I added a couple extra pieces of metadata to track tooling. 
Not included in these changes were the workers per-node, which I set to 1 in my funcx config.
=> feat: Switch GPU flow to prod index, add metadata to track corr_gpu tooling

gladier_xpcs/tools/xpcs_boost_corr.py
Previously, logs would be appended run-over-run, causing logs
to become large and hard to read.
=> fix: Logging on boost_corr step to overwrite logs on each run

gladier_xpcs/tools/plot.py
During testing, the image files were being dropped into a separate nested A001_Aerogel directory above. The changes above fix this to ensure files are dropped into the current directory instead, which is the location images were previously saved.
=> fix: location XPCS Webplot is dropping image files

scripts/dm/workflow-xpcs8-02-gladier-boost.py, scripts/xpcs_online_boost_client.py
Only Multitau or both is supported. Both computes twotime but does
not use it for plotting or metadata.
=> fix: Revert option for specifying 'Twotime'

scripts/batch_status.py
20 minutes wasn't nearly enough for requests that take several minutes.
Bump it up to a week.
=> fix: Bump cache time on batch processing

gladier_xpcs/deployments.py, scripts/xpcs_online_boost_client.py
This is the "easy" fix for switching to Eagle. The transfer is still applicable for moving this to a writable location for processing. I've had trouble getting direct processing working on an Eagle location where I'm not explicitly added to the group.
=> Switch my deployment and default datasets to pull from Eagle instead of Clutch

README.md
Using nvida would install a non-gpu cpu version of torch which would raise exceptions during boost_corr
=> Update env setup to use specific cuda/torch requirements

README.md, gladier_xpcs/collections.py, gladier_xpcs/deployments.py, gladier_xpcs/flows/flow_boost.py, gladier_xpcs/tools/__init__.py, gladier_xpcs/tools/source_transfer.py, requirements.txt, scripts/xpcs_online_boost_client.py
This is a first stab at a common pathing problem in flows: POSIX paths map to different locations than Globus Shared Endpoint paths.
Mainly, this introduces the SharedCollection path which tracks the POSIX path associated with a Globus share. Paths can then be 'translated' to either posix or globus paths as needed.
=> feat: Abstract collections to make path information routable

scripts/xpcs_online_boost_client.py
The recent change to abstracting paths for guest collections changed the input paths for files to treat them as if they were 'POSIX' paths.
However, DM is setup to start runs with inputs using 'Globus' paths, which broke runs from DM. Reverting to the old style fixes this.
=> fix: Revert 'POSIX' source input paths for 'Globus' paths

requirements.txt, scripts/get_status.py, tests/reprocessing_tools/test_reprocessing.py
This switches the old `get_ordered_flow_states` out for the newer flow iteration tools which use branching. This is still an internal call to gladier utils, and it does do a depth first fetch of all states (which probably isn't what we want, but is fine for now).
=> fix: DM Status reporting, allow upgrading to Gladier 0.8.x

xpcs_portal/xpcs_index/fields.py
This fixes records like the following:
https://acdc.alcf.anl.gov/xpcs/detail/globus%253A%252F%252F74defd5b-5f61-42fc-bcc4-834c9f376a4f%252FXPCSDATA%252FAutomate%252F2024-1%252Fzhang202402_2%252FH001_27445_QZ_XPCS_test-01000/
Which now use publish v2.
=> fix: remote files loading in newly published records

scripts/xpcs_online_boost_client.py
Processed data will automatically be transferred back to source, using the source filenames to determine the paths with some assumptions.
This operation can still be skipped if its test data or if reprocessing data at a later time when write access is no longer allowed on the directory.
=> feat: Automatically determine path for transferring back processed data

gladier_xpcs/flows/flow_boost.py
Previously this was taken offline, and we needed to get it renewed. We can once again publish to this location
=> feat: Re-enable publishing now that Suresh's eagle endpoint is active again
