globus-gladier/gladier-xpcs

xpcs_client/manifest_reprocessing.py

@ravescovi Here are only the manifest reprocessing changes for Suresh's April 7th run. I'll add repo-specific changes to a separate PR.

Added manifest-reprocessing for Suresh's run on April 7th

---

gladier_xpcs/tools/pre_publish.py
requirements.txt

This **does not** fix regular publish. Need to do a quick update on Gladier tools

Added fix for pre-publish

---

gladier_xpcs/online_processing.py

I missed committing this change last night. Sigh.

Fixed override not properly specifying indexed value.

---

gladier_xpcs/client_online_corr.py
gladier_xpcs/tools/corr.py
gladier_xpcs/tools/plot.py
gladier_xpcs/tools/pre_publish.py

This allows us to reuse these values for Reprocessing

Move wait times to tool definitions instead of client definitions

---

xpcs_portal/README.md

Thanks Tyler for finding these!

fix: Readme

---

gladier_xpcs/tools/corr.py

Thanks Hannah for finding this!

fix: Make corr 'flags' flow input option default

---

requirements-portal.txt

We're on pypi now! No more installing from github!

bump DGPF to alpha on pypi

---

scripts/dm/workflow-xpcs8-01-gladier.py
scripts/get_status.py

Fixed some bugs with get_status, and added better error reporting in DM.

get_status.py overhaul

---

tests/test_get_status.py

Added a couple unit tests for this, because it's pretty rare we get
flows errors due to unexpected status responses.

Add tests for get_status

---

scripts/batch_status.py

This is a quick and dirty script written just before run day tomorrow
to check the status of many runs in a batch, and retry if needed.
Should be everythig we need!

feat: Get info on status of many runs in a batch

---

xpcs_portal/xpcs_index/management/commands/xpcs_image_filters.py

Small fix from the move to stand-alone repos

fix: Image filters command

---

xpcs_portal/xpcs_index/apps.py
xpcs_portal/xpcs_index/fields.py
xpcs_portal/xpcs_index/templates/xpcs/globus-portal-framework/v2/detail-overview.html
xpcs_portal/xpcs_index/views.py

Mainly, this adds text outputs to the detail metadata fields for issue #63. Additionally it adds some other fixes to the page, mostly for styling. 
I noticed a couple more small things to fix, I'll get to those after lunch.

Detail page improvements

---

.github/workflows/test_flow.yml

Flow testing is brittle and isn't really worth the hassle

chore: Stop flow testing for now

---

gladier_xpcs/tools/gather_xpcs_metadata.py
gladier_xpcs/tools/xpcs_boost_corr.py
scripts/xpcs_online_boost_client.py

Refactored the corr state to delete duplicated code and allow passing through custom values for previously hardcoded values.

Boost corr refactor

---

gladier_xpcs/tools/xpcs_boost_corr.py

Setup logging to capture output from boost_corr tool.

feat: Capture boost_corr logging

---

scripts/batch_status.py

Changes:
* flow_id must always be provided. Assuming the local flow was a bit confusing
Improvements:
* Caching -- Fetching runs will always save them to /tmp. Using the --cached flag
will re-use the file saved in the cache. Useful for > 100 runs
* Multi-retry -- Allow retrying batches of runs at a time.

feat: Improve batch_status.py -- caching, multi-retry

---

gladier_xpcs/tools/plot.py

I couldn't get plotting working reliably on the server. Either existing loggers are conflicting with the one set in the funcx function or the logger simply wouldn't output any logs when running on a funcx endpoint. 
I took out the logging for now and made some other minor fixes to the plotting code. The following works fine when tested on my funcx endpoint.

refactor: Clean up plotting

---

scripts/batch_status.py

Small improvements for the batch_status.py mini-CLI.

Batch status improvements

---

scripts/get_status.py

Add support for specifying client credential environment variables when performing get_status.py.

Support client credentials in get_status.py

---

gladier_xpcs/tools/gather_xpcs_metadata.py

Unfortunately, ensuring this fixed it has taken some time with the Polaris nodes currently tied up:
https://app.globus.org/runs/abffe93b-d21b-43bc-b676-9b5601efb8fb/logs

fix: Metadata to include signed ints

---

scripts/xpcs_online_boost_client.py

Fix for a problem where starting many flows creates new tokens on each invocation, potentially causing significant load on auth. Caching tokens re-uses them and fixes the problem

feat: Add token storage for use by confidential client

---

scripts/xpcs_online_boost_client.py

If many processses corrupt the save file, ignore the error and let the next grant save over and repair it.

fix: Possible multi-write corruption issue in DM

---

scripts/xpcs_online_boost_client.py

Discard expired tokens for a new grant

fix: Cached tokens expiring and improperly being reused

---

gladier_xpcs/deployments.py
gladier_xpcs/flows/flow_boost.py
gladier_xpcs/flows/flow_reprocess.py
scripts/xpcs_online_boost_client.py
tests/reprocessing_tools/test_reprocessing.py
xpcs_portal/testing/settings.py
xpcs_portal/xpcs_index/apps.py
xpcs_portal/xpcs_index/flows.py
xpcs_portal/xpcs_index/forms.py
xpcs_portal/xpcs_index/search.py
xpcs_portal/xpcs_index/search_collector.py
xpcs_portal/xpcs_index/templates/xpcs/globus-portal-framework/v2/components/search-result.html
xpcs_portal/xpcs_index/templates/xpcs/reprocess-datasets-checkout-form.html
xpcs_portal/xpcs_index/templates/xpcs/reprocess-datasets-checkout.html
xpcs_portal/xpcs_index/views.py

Bring back the old XPCS Reprocessing page with newer customized Django Crispy Forms.

Resurrect reprocessing

---

gladier_xpcs/deployments.py

Adds a new deployment config for NERSC.

Include a deployment for Ryan at NERSC

---

gladier_xpcs/tools/result_transfer.py
gladier_xpcs/tools/source_transfer.py

Note: This requires Gladier Tools v0.5.4

fix: Upgrade old transfer action provider to newer one

---

gladier_xpcs/tools/source_transfer.py

We've been seeing lots of timeouts with the current timeout being set to 60 seconds

Increase Source Transfer time
